doors:
  build: ./doors
  volumes:
    - "./data/doors/home/:/var/doors/.doors/"
  links:
    - mail:mail
  # ports:
  #   - 8989:8989
mail:
  build: ./mail
  environment:
    - HOST=doors.iscpif.fr
  dns:
    # we assume this is the local DNS
    - 192.168.1.1
  volumes:
    - "./data/mail/spool:/var/spool/postfix"
https-portal:
  image: steveltn/https-portal
  ports:
    - 8080:80
    - 8443:443
  links:
    - doors
  environment:
    - "DOMAINS=localhost -> http://doors:8989"
    #- "CLIENT_MAX_BODY_SIZE=4G"
    #- "STAGE=production"
    #- "STAGE=staging"
    - "STAGE=local"
